[global]
monitor_interval = 50
native = false
exit_on_injected = false

[base]
"x86.exe" = '.\dlls\x86\msg.dll'
"x64.exe" = '.\dlls\x64\msg.dll'

# execute when module exists
[module]
"x86.exe" = "user32.dll"

# execute when window title exists
[window]
"x86.exe" = "window title"

# TODO deferred x seconds execution
[delay]
"x86.exe" = 1
