[global]
monitor_interval = 50
native = false

[base]
"x86.exe" = '.\dlls\x86\msg.dll'
"x64.exe" = '.\dlls\x64\msg.dll'

[module]
"x86.exe" = "user32.dll"

[window]
"x86.exe" = "window title"

# TODO
[delay]
"x86.exe" = 1
