[global]
mode = 'native' # 'native' 'yapi' 'wow64ext'
exit = false # exit after injection

[easy] # optional
'x86.exe' = 'dlls/x86.dll'

[[mix]]
name = 'x86.exe'
dll = 'dlls/x86.dll'
delay = 0 # optional

[mix.limit] # optional
module = 'user32.dll' # optional
gui = true # optional

[[mix]]
name = 'x64.exe'
dll = 'dlls/x64.dll'

[mix.limit]
module = 'ws2_32.dll'
