[global]
# monitor interval 50ms
monitor_interval = 50

# use native method to inject
native = false

# exit after injection
exit_on_injected = false

[base]
"a.exe" = 'a.dll'
"b.exe" = '../b.dll'
"c.exe" = 'c:\c.dll'

"x86.exe" = '.\dlls\x86\msg.dll'
"x64.exe" = '.\dlls\x64\msg.dll'

# execute when module exists
[module]
"x86.exe" = "user32.dll"

# execute when window title exists
[window]
"x86.exe" = "window title"

# deferred x seconds execution, 5000 ms
[delay]
"x86.exe" = 5000
